### PR TITLE
Katherine update preproc for tablet

### PR DESCRIPTION
**Pull request by katherineperks**
Made some changes so that data collected on the 'tablet' rig can be preprocessed! Still a work in progress as I check that preprocessed tablet data has the fields needed to use typical functions in the analysis pipeline.

Note: The changes made to `get_interp_kinematics()` involving the clock are necessary to be able to use this function on preprocessed tablet data. The other changes to this function (i.e. adding new datatype options) are NOT necessary for preprocessing of tablet data to work and are just useful features I meant to add on another branch.

### CODE REVIEW

**Comment by leoscholl** [comment]
This all looks good, can you also update the tests to include the various kinematics on both rig and tablet data?

**Review by leoscholl — APPROVED** [review]
Made a couple comments, overall it looks good. Be careful when merging it looks like some other changes have been made with the same files.

**Comment by katherineperks** [comment]
I accidentally merged with another branch `katherine-tabulate-tracking-task` and having trouble undoing this

**Comment by katherineperks** [comment]
It looks like the the changes were reverted, but all the commits from the other branch are still listed.

**Comment by leoscholl** [comment]
It doesn’t look fixed to me. I would just check out the last good commit a07fc3d, make a new branch and a new pull request from there, and close this one.

**Pull request closed without merging**
